### ISSUE TITLE
Неработоспособность TF2R/Follx/OpiumPulses

### ISSUE THREAD

**Issue by cyber01** [pumPCin/GiveawayJoiner#10]
У указанных сервисов GiveawayJoiner пишет, что поиск раздач, но в итоге так и не находит ничего.

**Comment by pumPCin** [comment]
версия последняя? какие настройки у сервисов?

**Comment by cyber01** [comment]
версия f
Настройки дефолтные, только количество страниц до 30 поднял (чтобы старое проверил)

**Comment by pumPCin** [comment]
насчет tf2r, я этим сервисом не занимаюсь ничего про него не скажу, как был сделан автором, так он и не тронут, оставил для тех кто пользуется, может вообще и не работать, но вроде как говорят постом выше что работает

насчет follx сейчас там 4 раздачи, может они у вас есть в стиме? прога не вступает в них, если включено 'Проверять наличие в Steam'.

на opiumpulses столько страниц перебор, 2-3 там максимум бывает, и смысла нет ставить больше, прога пробует все эти страницы загрузить, сайт может просто блокирует такие потоки запросов, плюс на дефолтный таймер стоит 5 минут, этого мало чтобы проверить столько страниц, к примеру на astats.nl 40 раздач проверить на первой странице занимает около 5-7 минут

и дефолтными не нужно пользоваться, они просто первоначальные

**Comment by cyber01** [comment]
Можете тогда подсказать рекомендуемые параметры? Для каждого из сервисов

**Comment by BadSanta1980** [comment]
cyber1
tf2, follx по одной странице. на этих сайтах раздач практически нет! если за сутки добавят одну-две то хорошо... поэтому если написано поиск раздач, значит их нет... когда появится тогда прога и зайдёт
opiumpulse две страницы.
таймеры поставь по 720 минут.. чаще всё равно смысла нет... на этих сайтах фастов нету.
astats только одна страница
steamgifts не больше 15 страниц, хотя в реале 10
indiegala по разному.. бывает и до 15 страниц опускается, а бывает и больше 30 страниц на сайте. так что если 20 поставишь, не промахнёшься, всё равно поинтов не хватит))

**Comment by cyber01** [comment]
С версией g и подробным логированием - все сервисы ожили (хотя похоже на astats я забанен, а tf2r похоже уже труп).
