### ISSUE TITLE
Unable to connect to lootboy

### ISSUE THREAD

**Issue by MajorLOL** [pumPCin/GiveawayJoiner#19]
Greetings,

The tutorial was a bit unclear maybe because of the translation of google i dunno.
Currently i am receiving:
![image](https://user-images.githubusercontent.com/56225967/130756946-1b2321e6-da8e-4f2b-95d6-a92b83f9e0f9.png)

This is my current format:
![image](https://user-images.githubusercontent.com/56225967/130757164-c8bcfaa2-4c8b-4167-9672-0459fd6aa3ca.png)
at the end is nothing only the authentication numer.

Can anyone tell me what i am doing wrong? and maybe an English translate of wiki?

**Comment by pumPCin** [comment]
not need "user_id" word in file

For example in lootboy1.txt : 
6f07a2f72595b00024121r5g,Bearer tyJhbGciOiJSUzI1NiJ9.eyJ1c2VyIjoiNWYwMGE,

**Comment by MajorLOL** [comment]
Thanks that fixed it.

**Comment by pumPCin** [comment]
> Thanks that fixed it.

Glad to help!
